name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.5.0
  - ipywidgets=8.0.0
  - seaborn=0.11.1
  - pip=22.2.2
  - mlflow=1.30
  - pandas=1.2.4
  - pyarrow=2.0
  - pip:
    - wandb==0.13.4
    - protobuf==3.19.*
    - pandas-profiling[notebook,unicode]